settings = dict()
settings['pop_size'] = 5 # number of agents to spawn
settings['pop_size 2'] = 20
settings['food_quant'] = 80
settings['color'] = 'green'
settings['x_min'] = 20  # left side of the arena
settings['x_max'] = 1050  # right side of the arena
settings['y_min'] = 20  # lower bound of the arena
settings['y_max'] = 825  # upper bound of the arena
settings['traps_quant'] = 0
settings['bad_agents_quant'] = 0
settings['food_creators_quant'] = 0
settings['mutation_rate'] = 0.1
settings['number_of_test'] = 5
